CASMPET-6814: Add new RPMs for spire TPM
Cray-HPE/csm pull request #2929
Opened 2023-09-29 21:13 UTC by ndavidson-hpe

## Summary and Scope

Add new RPMs to the CSM config for enablement of TPM on compute nodes.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMPET-6814](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6814)

## Testing

### Tested on:

  * Baldar

### Test description:

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?y
- Were continuous integration tests run? If not, why?y
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests (or test issues/Jiras) created for this change?y

## Risks and Mitigations

Low risk only adds functionality

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2023-09-29 21:13 UTC, ndavidson-hpe commented
/backport release/1.6

2024-01-05 17:36 UTC, mharding-hpe requested changes
The csm-config version will also need to be bumped, to pick up the changes from that PR. I'll add a commit for that once I have the version numbers.

2024-01-05 18:05 UTC, mharding-hpe approved these changes

2024-01-05 19:13 UTC, heemstra approved these changes

2024-01-05 19:13 UTC, merged