canu release
Cray-HPE/csm pull request #881
Opened 2022-06-02 23:49 UTC by kosonenj

## Summary and Scope

Upgrading Canu from 1.5.7 to 1.6.1.

    Disable load balacing configuration for Dell CDU/Leaf.
    Add canu report network version feature.
    Fix Errors in the output of canu test
    Add route-map and prefixes to allow connection to UAI's from CAN network.
    Fix Dell4148 template to include correct port count

## Issues and Related PRs

https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3322
https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1572

## Testing

Nox, surtur, drax

### Test description:

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-06-03 16:45 UTC, rustydb requested changes
This is changing a lot, holding so i can take a closer look in a few minutes

2022-06-04 14:26 UTC, heemstra approved these changes

2022-06-04 15:00 UTC, rustydb approved these changes

2022-06-04 15:06 UTC, rustydb requested changes

2022-06-04 15:06 UTC, rustydb commented on rpm/cray/csm/sle-15sp3/index.yaml
> -    - canu-1.5.12-1.x86_64
Why is this moving back to sp2?

2022-06-04 15:21 UTC, rustydb approved these changes

2022-06-04 16:24 UTC, mtupitsyn approved these changes

2022-06-04 16:24 UTC, merged